### PR TITLE
Updated to Firebase 3.2.0

### PR DESCRIPTION
**Pull request by TimKreger-IA**
Updated Podspec
Updated tests

### CODE REVIEW

**Comment by TimKreger-IA** [comment]
Third time lucky?
@mcdonamp  @jwngr

**Comment by mcdonamp** [comment]
Sorry about CLA bot being so picky--I'll get this done tonight :)

**Comment by TimKreger-IA** [comment]
@mcdonamp No probs, most of the problems were my own doing!

**Comment by psopher** [comment]
@TimKreger-IA  and @mcdonamp, thanks so much for your contributions to upgrading Geofire. Any idea when it'll be ready? I have an app that requires Geofire and have been wondering when it will be possible to upgrade to the new Firebase. I know inquiries of this sort can be annoying, so sorry if that's the case. For me and others like me a time estimate would be helpful for planning our days!

Thanks again!

**Comment by wilsonbalderrama** [comment]
I want to thank to @TimKreger-IA for doing this awesome contribution, great example, I am going to start contributing too!

Yeah this library is crucial for many apps nowadays geo queries is so popular!

**Comment by mcdonamp** [comment]
Ok, there are a still a few changes that need to be made here (`setup.sh` doesn't work anymore, we'll need to bump the version number in the podspec), but I ran it and the tests pass so I'll merge and then make those changes.

**Pull request merged**
