### PR TITLE
Updated to FireBase 3.2

### PR DESCRIPTION
**Pull request by TimKreger-IA**
Updated podspec
Updated sourcefiles
Updated tests.

### CODE REVIEW

**Comment by TimKreger-IA** [comment]
@mcdonamp Hi Michael, made a complete mess of the other fork by commiting with a private email. Reforked and redid.
This has lost your comments but I think I've addressed the all of the issues.

**Comment by TimKreger-IA** [comment]
I signed it

**Comment by TimKreger-IA** [comment]
Not sure what the deal is with CLA

**Comment by jwngr** [comment]
@TimKreger-IA - It looks like you didn't commit with the correct GitHub email address or username. If you look in the "Commits" tab, you'll see the commit has your name but doesn't link to your account. Can you please try again?

**Comment by TimKreger** [comment]
Yeah, I'll redo at work where my identity is consistent

**Comment by TimKreger-IA** [comment]
redoing from proper identity

**Pull request closed without merging**
